# Generated by Django 5.2.1 on 2025-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeaType',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tea_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
